const SelectedUserActionTypes = {
  GET_SELECTED_USER_START: 'GET_SELECTED_USER_START',
  GET_SELECTED_USER_SUCCESS: 'GET_SELECTED_USER_SUCCESS',
  GET_SELECTED_USER_FAILURE: 'GET_SELECTED_USER_FAILURE'
};

export default SelectedUserActionTypes;
