const UserActionTypes = {
  SIGNUP_USER_START: 'SIGNUP_USER_START',
  SIGNUP_USER_SUCCESS: 'SIGNUP_USER_SUCCESS',
  SIGNUP_USER_FAILURE: 'SIGNUP_USER_FAILURE',
  SIGNIN_USER_START: 'SIGNIN_USER_START',
  SIGNIN_USER_SUCCESS: 'SIGNIN_USER_SUCCESS',
  SIGNIN_USER_FAILURE: 'SIGNIN_USER_FAILURE',
  LOADING_USER_START: 'LOADING_USER_START',
  LOADING_USER_SUCCESS: 'LOADING_USER_SUCCESS',
  LOADING_USER_FAILURE: 'LOADING_USER_FAILURE',
  SIGNOUT_USER_START: 'SIGNOUT_USER_START',
  SIGNOUT_USER_SUCCESS: 'SIGNOUT_USER_SUCCESS',
  SIGNOUT_USER_FAILURE: 'SIGNOUT_USER_FAILURE',
  EDIT_USER_PROFILE_START: 'EDIT_USER_PROFILE_START',
  EDIT_USER_PROFILE_SUCCESS: 'EDIT_USER_PROFILE_SUCCESS',
  EDIT_USER_PROFILE_FAILURE: 'EDIT_USER_PROFILE_FAILURE'
};

export default UserActionTypes;
