const UserActionTypes = {
  SIGNUP_USER_START: 'SIGNUP_USER_START',
  SIGNUP_USER_SUCCESS: 'SIGNUP_USER_SUCCESS',
  SIGNUP_USER_FAILURE: 'SIGNUP_USER_FAILURE',

  SIGNIN_USER_START: 'SIGNIN_USER_START',
  SIGNIN_USER_SUCCESS: 'SIGNIN_USER_SUCCESS',
  SIGNIN_USER_FAILURE: 'SIGNIN_USER_FAILURE',

  LOADING_USER_START: 'LOADING_USER_START',
  LOADING_USER_SUCCESS: 'LOADING_USER_SUCCESS',
  LOADING_USER_FAILURE: 'LOADING_USER_FAILURE',

  SIGNOUT_USER_START: 'SIGNOUT_USER_START',
  SIGNOUT_USER_SUCCESS: 'SIGNOUT_USER_SUCCESS',
  SIGNOUT_USER_FAILURE: 'SIGNOUT_USER_FAILURE',

  EDIT_USER_PROFILE_START: 'EDIT_USER_PROFILE_START',
  EDIT_USER_PROFILE_SUCCESS: 'EDIT_USER_PROFILE_SUCCESS',
  EDIT_USER_PROFILE_FAILURE: 'EDIT_USER_PROFILE_FAILURE',

  EDIT_BOOK_START: 'EDIT_BOOK_START',
  EDIT_BOOK_SUCCESS: 'EDIT_BOOK_SUCCESS',
  EDIT_BOOK_FAILURE: 'EDIT_BOOK_FAILURE',

  GET_USER_BOOKS_START: 'GET_USER_BOOKS_START',
  GET_USER_BOOKS_SUCCESS: 'GET_USER_BOOKS_SUCCESS',
  GET_USER_BOOKS_FAILURE: 'GET_USER_BOOKS_FAILURE',

  EDIT_COLLECTION_START: 'EDIT_COLLECTION_START',
  EDIT_COLLECTION_SUCCESS: 'EDIT_COLLECTION_SUCCESS',
  EDIT_COLLECTION_FAILURE: 'EDIT_COLLECTION_FAILURE',

  GET_USER_COLLECTIONS_START: 'GET_USER_COLLECTIONS_START',
  GET_USER_COLLECTIONS_SUCCESS: 'GET_USER_COLLECTIONS_SUCCESS',
  GET_USER_COLLECTIONS_FAILURE: 'GET_USER_COLLECTIONS_FAILURE',

  GET_USER_NOTIFICATIONS_START: 'GET_USER_NOTIFICATIONS_START',
  GET_USER_NOTIFICATIONS_SUCCESS: 'GET_USER_NOTIFICATIONS_SUCCESS',
  GET_USER_NOTIFICATIONS_FAILURE: 'GET_USER_NOTIFICATIONS_FAILURE',

  UPDATE_NOTIFICATION_START: 'UPDATE_NOTIFICATION_START',
  UPDATE_NOTIFICATION_SUCCESS: 'UPDATE_NOTIFICATION_SUCCESS',
  UPDATE_NOTIFICATION_FAILURE: 'UPDATE_NOTIFICATION_FAILURE',

  DELETE_BOOK_START: 'DELETE_BOOK_START',
  DELETE_BOOK_SUCCESS: 'DELETE_BOOK_SUCCESS',
  DELETE_BOOK_FAILURE: 'DELETE_BOOK_FAILURE',

  DELETE_COLLECTION_START: 'DELETE_COLLECTION_START',
  DELETE_COLLECTION_SUCCESS: 'DELETE_COLLECTION_SUCCESS',
  DELETE_COLLECTION_FAILURE: 'DELETE_COLLECTION_FAILURE',

  CHANGE_PASSWORD_START: 'CHANGE_PASSWORD_START',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  FORGET_PASSWORD_START: 'FORGET_PASSWORD_START',
  FORGET_PASSWORD_SUCCESS: 'FORGET_PASSWORD_SUCCESS',
  FORGET_PASSWORD_FAILURE: 'FORGET_PASSWORD_FAILURE',

  DELETE_USER_START: 'DELETE_USER_START',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',

  ADD_FAVOURITE_START: 'ADD_FAVOURITE_START',
  ADD_FAVOURITE_SUCCESS: 'ADD_FAVOURITE_SUCCESS',
  ADD_FAVOURITE_FAILURE: 'ADD_FAVOURITE_FAILURE',

  REMOVE_FAVOURITE_START: 'REMOVE_FAVOURITE_START',
  REMOVE_FAVOURITE_SUCCESS: 'REMOVE_FAVOURITE_SUCCESS',
  REMOVE_FAVOURITE_FAILURE: 'REMOVE_FAVOURITE_FAILURE',

  GET_USER_FAVOURITES_START: 'GET_USER_FAVOURITES_START',
  GET_USER_FAVOURITES_SUCCESS: 'GET_USER_FAVOURITES_SUCCESS',
  GET_USER_FAVOURITES_FAILURE: 'GET_USER_FAVOURITES_FAILURE',

  SET_SELECTED_ITEM: 'SET_SELECTED_ITEM',
  CLEAR_SELECTED_ITEM: 'CLEAR_SELECTED_ITEM'
};

export default UserActionTypes;
