const ChatsActionTypes = {
  GET_USER_UNSEEN_MSGS_COUNT_START: 'GET_USER_UNSEEN_MSGS_COUNT_START',
  GET_USER_UNSEEN_MSGS_COUNT_SUCCESS: 'GET_USER_UNSEEN_MSGS_COUNT_SUCCESS',
  GET_USER_UNSEEN_MSGS_COUNT_FAILURE: 'GET_USER_UNSEEN_MSGS_COUNT_FAILURE',

  GET_USER_BASIC_CHATS_START: 'GET_USER_BASIC_CHATS_START',
  GET_USER_BASIC_CHATS_SUCCESS: 'GET_USER_BASIC_CHATS_SUCCESS',
  GET_USER_BASIC_CHATS_FAILURE: 'GET_USER_BASIC_CHATS_FAILURE',

  GET_CHAT_START: 'GET_CHAT_START',
  GET_CHAT_SUCCESS: 'GET_CHAT_SUCCESS',
  GET_CHAT_FAILURE: 'GET_CHAT_FAILURE',

  PUSH_MSG_TO_CURRENT_CHAT: 'PUSH_MSG_TO_CURRENT_CHAT'
};

export default ChatsActionTypes;
