const ChatsActionTypes = {
  GET_USER_UNSEEN_MSGS_COUNT_START: 'GET_USER_UNSEEN_MSGS_COUNT_START',
  GET_USER_UNSEEN_MSGS_COUNT_SUCCESS: 'GET_USER_UNSEEN_MSGS_COUNT_SUCCESS',
  GET_USER_UNSEEN_MSGS_COUNT_FAILURE: 'GET_USER_UNSEEN_MSGS_COUNT_FAILURE',

  GET_USER_BASIC_CHATS_START: 'GET_USER_BASIC_CHATS_START',
  GET_USER_BASIC_CHATS_SUCCESS: 'GET_USER_BASIC_CHATS_SUCCESS',
  GET_USER_BASIC_CHATS_FAILURE: 'GET_USER_BASIC_CHATS_FAILURE',

  GET_CHAT_START: 'GET_CHAT_START',
  GET_CHAT_SUCCESS: 'GET_CHAT_SUCCESS',
  GET_CHAT_FAILURE: 'GET_CHAT_FAILURE',

  REMOVE_CHAT_COPY_START: 'REMOVE_CHAT_COPY_START',
  REMOVE_CHAT_COPY_SUCCESS: 'REMOVE_CHAT_COPY_SUCCESS',
  REMOVE_CHAT_COPY_FAILURE: 'REMOVE_CHAT_COPY_FAILURE',

  UPDATE_CHAT_MSGS_SEEN_START: 'UPDATE_CHAT_MSGS_SEEN_START',
  UPDATE_CHAT_MSGS_SEEN_SUCCESS: 'UPDATE_CHAT_MSGS_SEEN_SUCCESS',
  UPDATE_CHAT_MSGS_SEEN_FAILURE: 'UPDATE_CHAT_MSGS_SEEN_FAILURE'
};

export default ChatsActionTypes;
