const PublicItemsActionTypes = {
  GET_ALL_PUBLIC_ITEMS_START: 'GET_ALL_PUBLIC_ITEMS_START',
  GET_ALL_PUBLIC_ITEMS_SUCCESS: 'GET_ALL_PUBLIC_ITEMS_SUCCESS',
  GET_ALL_PUBLIC_ITEMS_FAILURE: 'GET_ALL_PUBLIC_ITEMS_FAILURE',

  SEARCH_ITEMS_START: 'SEARCH_ITEMS_START',
  SEARCH_ITEMS_SUCCESS: 'SEARCH_ITEMS_SUCCESS',
  SEARCH_ITEMS_FAILURE: 'SEARCH_ITEMS_FAILURE'
};

export default PublicItemsActionTypes;
