const PublicItemsActionTypes = {
  GET_ALL_PUBLIC_ITEMS_START: 'GET_ALL_PUBLIC_ITEMS_START',
  GET_ALL_PUBLIC_ITEMS_SUCCESS: 'GET_ALL_PUBLIC_ITEMS_SUCCESS',
  GET_ALL_PUBLIC_ITEMS_FAILURE: 'GET_ALL_PUBLIC_ITEMS_FAILURE'
};

export default PublicItemsActionTypes;
