const ConversioReatesActionTypes = {
  GET_CONVERSION_RATES_START: 'GET_CONVERSION_RATES_START',
  GET_CONVERSION_RATES_SUCCESS: 'GET_CONVERSION_RATES_SUCCESS',
  GET_CONVERSION_RATES_FAILURE: 'GET_CONVERSION_RATES_FAILURE'
};

export default ConversioReatesActionTypes;
