const UserActionTypes = {
  REGISTER_USER_START: 'REGISTER_USER_START',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',
  SIGNIN_USER_START: 'SIGNIN_USER_START',
  SIGNIN_USER_SUCCESS: 'SIGNIN_USER_SUCCESS',
  SIGNIN_USER_FAILURE: 'SIGNIN_USER_FAILURE',
  LOADING_USER_START: 'LOADING_USER_START',
  LOADING_USER_SUCCESS: 'LOADING_USER_SUCCESS',
  LOADING_USER_FAILURE: 'LOADING_USER_FAILURE',
  SIGNOUT_USER_START: 'SIGNOUT_USER_START',
  SIGNOUT_USER_SUCCESS: 'SIGNOUT_USER_SUCCESS',
  SIGNOUT_USER_FAILURE: 'SIGNOUT_USER_FAILURE'
};

export default UserActionTypes;
